### ISSUE TITLE
Ошибка в  схеме 

### ISSUE THREAD

**Issue by novicov** [MicrosoftDocs/architecture-center.ru-ru#3]
Ошибка в написании.
Последняя схема, ошибка в написании "обноление"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: e46426ef-bb0f-b085-a645-7e3e6c05752d
* Version Independent ID: 13b0c53a-cd01-9894-f34f-8d223c8e5b2b
* Content: [Стиль архитектуры CQRS - Azure Application Architecture Guide](https://docs.microsoft.com/ru-ru/azure/architecture/guide/architecture-styles/cqrs#feedback)
* Content Source: [docs/guide/architecture-styles/cqrs.md](https://github.com/microsoftdocs/architecture-center.ru-ru/blob/live/docs/guide/architecture-styles/cqrs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Здравствуйте, @novicov 
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @novicov
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/azure/architecture/guide/architecture-styles/cqrs#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
