### ISSUE TITLE
Incorrect russian translation in third paragraph, second sentence

### ISSUE THREAD

**Issue by PrefixCoder** [MicrosoftDocs/architecture-center.ru-ru#6]
In Russian version is says:
"In practice, "NoSQL" means "non-relational database," even though many of these databases DON'T support SQL-compatible queries"  
instead of:
"In practice, "NoSQL" means "non-relational database," even though many of these databases DO support SQL-compatible queries"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: aca5ad7e-2611-198b-6327-d253f5519964
* Version Independent ID: 19059344-22ca-3103-efb8-df3820d92c9e
* Content: [Нереляционные данные и базы данных NoSQL](https://docs.microsoft.com/ru-ru/azure/architecture/data-guide/big-data/non-relational-data#feedback)
* Content Source: [docs/data-guide/big-data/non-relational-data.md](https://github.com/microsoftdocs/architecture-center.ru-ru/blob/live/docs/data-guide/big-data/non-relational-data.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @PrefixCoder
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @PrefixCoder
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/azure/architecture/data-guide/big-data/non-relational-data

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
